apiVersion: drasi.io/v1alpha1
kind: Reaction
metadata:
  name: reorder-reaction
  labels:
    drasi.io/demo: cncf-webinar
spec:
  kind: StoredProc
  queries:
    - reorder-monitoring-query
  properties:
    addedResultCommand: "SELECT public.add_order('{{ .supplier_id }}', '{{ .product_id }}', {{ .reorder_level }} * 2);"
    databaseClient: pg
    databaseHostname: host.docker.internal
    databasePort: 5432
    databaseUser: drasi_replication
    databaseDbname: inventory_management
    databasePassword: drasi_password
    databaseSsl: false