apiVersion: v1
kind: Source
name: inventory-management-source
spec:
  kind: PostgreSQL
  properties:
    host: host.docker.internal
    port: 5432
    user: drasi_replication
    password: drasi_password
    database: inventory_management
    ssl: false
    tables:
      - public.product
      - public.supplier_order
      - public.supplier_order_item