apiVersion: v1
kind: Source
metadata:
  name: inventory-management-source
  labels:
    drasi.io/demo: cncf-webinar
spec:
  kind: PostgreSQL
  services:
    - id: inventory-db
      endpoint: postgresql://postgres:password@localhost:5432/inventory_management
  tables:
    product:
      - supplier_id
      - name
      - description
      - price
      - reorder_level
    supplier_order:
      - supplier_id
      - order_date
      - delivery_date
    supplier_order_item:
      - order_id
      - product_id
      - quantity
      - price