apiVersion: v1
kind: Source
metadata:
  name: retail-operations-source
  labels:
    drasi.io/demo: cncf-webinar
spec:
  kind: PostgreSQL
  services:
    - id: retail-ops-db
      endpoint: postgresql://postgres:password@localhost:5432/retail_operations
  tables:
    customer_order:
      - customer_id
      - order_date
    customer_order_item:
      - order_id
      - product_id
      - quantity
      - price