apiVersion: v1
kind: Source
name: retail-operations-source
spec:
  kind: PostgreSQL
  properties:
    host: host.docker.internal
    port: 5432
    user: drasi_replication
    password: drasi_password
    database: retail_operations
    ssl: false
    tables:
      - public.customer_order
      - public.customer_order_item